# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/husky/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),husky)

$(call add-radio-file-sha1-checked,radio/abl.img,c55637c918e8b825da792d68d97e4a24084f4c44)
$(call add-radio-file-sha1-checked,radio/bl1.img,ed2ffdb10f2a0f880b87c241a225c65cdf622a48)
$(call add-radio-file-sha1-checked,radio/bl2.img,c7c99bc0662c1c18e4e70e7d12df698a277f2b8b)
$(call add-radio-file-sha1-checked,radio/bl31.img,2cef993d0b7267606600789e6ef314c1a85995d7)
$(call add-radio-file-sha1-checked,radio/gcf.img,9e32eda8c3306efd99e3c6fd71ae5fd61a40b15b)
$(call add-radio-file-sha1-checked,radio/gsa.img,0970703906fb682d04272cd32ab6323596cc9c10)
$(call add-radio-file-sha1-checked,radio/gsa_bl1.img,9b08526d3ed8db4282401cbd6cb0b66b98d916bd)
$(call add-radio-file-sha1-checked,radio/ldfw.img,25a73f0fd5705d4cb3e69345ce0b509d91ac3b00)
$(call add-radio-file-sha1-checked,radio/modem.img,82cd1f0ddf9359d4835e9f32c0af1e389a13d958)
$(call add-radio-file-sha1-checked,radio/pbl.img,8d3eeb29e1ce6efc425987bfd595f87ad142052b)
$(call add-radio-file-sha1-checked,radio/tzsw.img,4c4bbbcd849676717089b773ba8eaca8707c293c)

endif
