# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/husky/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),husky)

$(call add-radio-file-sha1-checked,radio/abl.img,f64dcf33de9c3f115f9bc41d41479e2d3bbcab6a)
$(call add-radio-file-sha1-checked,radio/bl1.img,43a50b13bf8185aa15443c2161683498c3a74e91)
$(call add-radio-file-sha1-checked,radio/bl2.img,60b659540385a3d21c8bdce6bb794401a72826a0)
$(call add-radio-file-sha1-checked,radio/bl31.img,5bfe4b45cc74802d0f68c9ecc793902ba0aca15a)
$(call add-radio-file-sha1-checked,radio/gcf.img,d85820ef518afb0cdd17598c7ae184df34b9c30d)
$(call add-radio-file-sha1-checked,radio/gsa.img,f7d17261b3c2489e468c3c45cdcc8269542327f0)
$(call add-radio-file-sha1-checked,radio/gsa_bl1.img,b8affa1d072e51fa9ff3cd26da0b77e60e2eaaa7)
$(call add-radio-file-sha1-checked,radio/ldfw.img,c72af8dce37eab0b96b7cdc116e9792ac6ede0c3)
$(call add-radio-file-sha1-checked,radio/modem.img,4d26806d0d9899b0c1762dcd18ac97d3065c278b)
$(call add-radio-file-sha1-checked,radio/pbl.img,81179026d695bedc55d15bdf43fa584b05357e74)
$(call add-radio-file-sha1-checked,radio/tzsw.img,52a04d63f3b1af0d7e6fad9dac074d7e4b955296)

endif
